(function() {var implementors = {};
implementors["finchers_cors"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"finchers_cors/struct.CorsFilter.html\" title=\"struct finchers_cors::CorsFilter\">CorsFilter</a>",synthetic:true,types:["finchers_cors::CorsFilter"]},{text:"impl&lt;E&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"finchers_cors/struct.CorsEndpoint.html\" title=\"struct finchers_cors::CorsEndpoint\">CorsEndpoint</a>&lt;E&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;E: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a>,&nbsp;</span>",synthetic:true,types:["finchers_cors::CorsEndpoint"]},{text:"impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"finchers_cors/struct.CorsResponse.html\" title=\"struct finchers_cors::CorsResponse\">CorsResponse</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a>,&nbsp;</span>",synthetic:true,types:["finchers_cors::CorsResponse"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"finchers_cors/struct.CorsError.html\" title=\"struct finchers_cors::CorsError\">CorsError</a>",synthetic:true,types:["finchers_cors::CorsError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"finchers_cors/enum.CorsErrorKind.html\" title=\"enum finchers_cors::CorsErrorKind\">CorsErrorKind</a>",synthetic:true,types:["finchers_cors::CorsErrorKind"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
