(function() {var implementors = {};
implementors["finchers_cors"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"finchers_cors/struct.CorsFilter.html\" title=\"struct finchers_cors::CorsFilter\">CorsFilter</a>",synthetic:false,types:["finchers_cors::CorsFilter"]},{text:"impl&lt;E:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"finchers_cors/struct.CorsEndpoint.html\" title=\"struct finchers_cors::CorsEndpoint\">CorsEndpoint</a>&lt;E&gt;",synthetic:false,types:["finchers_cors::CorsEndpoint"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"finchers_cors/struct.CorsResponse.html\" title=\"struct finchers_cors::CorsResponse\">CorsResponse</a>&lt;T&gt;",synthetic:false,types:["finchers_cors::CorsResponse"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"finchers_cors/struct.CorsError.html\" title=\"struct finchers_cors::CorsError\">CorsError</a>",synthetic:false,types:["finchers_cors::CorsError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"finchers_cors/enum.CorsErrorKind.html\" title=\"enum finchers_cors::CorsErrorKind\">CorsErrorKind</a>",synthetic:false,types:["finchers_cors::CorsErrorKind"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
